### ISSUE TITLE
the example can not handle one client

### ISSUE THREAD

**Issue by zjbbuaa** [paultan63/DTLS-epoll-example#1]
**Server.**
./dtls_server 127.0.0.1:9000                                                        # ~/DTLS-epoll-example-master
SSL_CTX_load_verify_location(): 1
SSL_CTX_set_default_verify_file(): 1
listen fd:4
BIO_s_custom_create: BIO[0x00000000026BDFC0]
<< INET: 127.0.0.1:58021
new connection: INET: 127.0.0.1:58021
BIO_s_custom_ctrl: BIO[0x00000000026BDFC0], cmd[50], num[1], ptr[0x0000000000000000]
BIO_s_custom_read: BIO[0x00000000026BDFC0], data[0x00000000026C3E80], dlen[16384], peekmode:1
  data[0x00000000026C1F98] queue_size: 1
  buf[0x00000000026C36A0] read len:189
BIO_s_custom_ctrl: BIO[0x00000000026BDFC0], cmd[50], num[0], ptr[0x0000000000000000]
BIO_s_custom_read: BIO[0x00000000026BDFC0], data[0x00000000026C3E80], dlen[16384], peekmode:0
  data[0x00000000026C1F98] queue_size: 1
  buf[0x00000000026C36A0] read len:189
BIO_s_custom_ctrl: BIO[0x00000000026BDFC0], cmd[50], num[1], ptr[0x0000000000000000]
BIO_s_custom_ctrl: BIO[0x00000000026BDFC0], cmd[46], num[0], ptr[0x00000000026C1970]
BIO_s_custom_ctrl: BIO[0x00000000026BDFC0], cmd[46], num[0], ptr[0x00000000026C1710]
BIO_s_custom_ctrl: BIO[0x00000000026BDFC0], cmd[44], num[0], ptr[0x00000000026C1710]
BIO_s_custom_write: BIO[0x00000000026BDFC0], buf[0x00000000026C3E80], dlen[48]
>> INET: 127.0.0.1:58021
  48 bytes sent
BIO_s_custom_ctrl: BIO[0x00000000026BDFC0], cmd[11], num[0], ptr[0x0000000000000000]
BIO_s_custom_read: BIO[0x00000000026BDFC0], data[0x00000000026C3E80], dlen[16384], peekmode:1
  data[0x00000000026C1F98] queue_size: 0
DTLSv1_listen():-1
<< INET: 127.0.0.1:58021
new connection: INET: 127.0.0.1:58021
BIO_s_custom_ctrl: BIO[0x00000000026BDFC0], cmd[50], num[1], ptr[0x0000000000000000]
BIO_s_custom_read: BIO[0x00000000026BDFC0], data[0x00000000026C3E80], dlen[16384], peekmode:1
  data[0x00000000026C1F98] queue_size: 1
  buf[0x00000000026C36A0] read len:209
BIO_s_custom_ctrl: BIO[0x00000000026BDFC0], cmd[46], num[0], ptr[0x00000000026C1970]
BIO_s_custom_ctrl: BIO[0x00000000026BDFC0], cmd[46], num[0], ptr[0x00000000026BF1C0]
BIO_s_custom_ctrl: BIO[0x00000000026BDFC0], cmd[50], num[0], ptr[0x0000000000000000]
DTLSv1_listen():1
BIO_s_custom_ctrl: BIO[0x00000000026BDFC0], cmd[6], num[0], ptr[0x00000000026BF1C0]
BIO_s_custom_read: BIO[0x00000000026BDFC0], data[0x00000000026C93E3], dlen[16717], peekmode:0
  data[0x00000000026C1F98] queue_size: 1
  buf[0x00000000026C36A0] read len:209
BIO_s_custom_read: BIO[0x00000000026BDFC0], data[0x00000000026C93E3], dlen[16717], peekmode:0
  data[0x00000000026C1F98] queue_size: 0
SSL_accept():-1
SSL_accept error syscall0
**client:**
./dtls_client 127.0.0.1:9000                                                        # ~/DTLS-epoll-example-master
SSL_CTX_load_verify_locations(): 1
SSL_CTX_set_default_verify_file(): 1
BIO_s_custom_create: BIO[0x000000000221B540]
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[6], num[0], ptr[0x00000000022193A0]
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[45], num[0], ptr[0x000000000221B478]
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[49], num[0], ptr[0x0000000000000000]
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[40], num[0], ptr[0x0000000000000000]
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[49], num[0], ptr[0x0000000000000000]
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[49], num[0], ptr[0x0000000000000000]
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[13], num[0], ptr[0x0000000000000000]
BIO_s_custom_write: BIO[0x000000000221B540], buf[0x000000000222C5F0], dlen[189]
>> INET: 127.0.0.1:9000
  189 bytes sent
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[11], num[0], ptr[0x0000000000000000]
BIO_s_custom_read: BIO[0x000000000221B540], data[0x00000000022233B3], dlen[16717], peekmode:0
  data[0x00007FFC297748C8] queue_size: 0
<< 48 bytes
BIO_s_custom_read: BIO[0x000000000221B540], data[0x00000000022233B3], dlen[16717], peekmode:0
  data[0x00007FFC297748C8] queue_size: 1
  buf[0x000000000221D670] read len:48
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[45], num[0], ptr[0x000000000221B478]
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[45], num[0], ptr[0x000000000221B478]
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[49], num[0], ptr[0x0000000000000000]
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[49], num[0], ptr[0x0000000000000000]
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[13], num[0], ptr[0x0000000000000000]
BIO_s_custom_write: BIO[0x000000000221B540], buf[0x000000000222C5F0], dlen[209]
>> INET: 127.0.0.1:9000
  209 bytes sent
BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[11], num[0], ptr[0x0000000000000000]
BIO_s_custom_read: BIO[0x000000000221B540], data[0x00000000022233B3], dlen[16717], peekmode:0
  data[0x00007FFC297748C8] queue_size: 0
>> BIO_s_custom_ctrl: BIO[0x000000000221B540], cmd[7], num[0], ptr[0x00000000022193A0]
BIO_s_custom_destroy: BIO[0x000000000221B540]

Do you know why?

**Comment by paultan63** [comment]
> **Server.**
> ./dtls_server 127.0.0.1:9000 # ~/DTLS-epoll-example-master
> > > SSL_accept():-1
> > > SSL_accept error syscall0

I don't know why SSL_accept fail。 Maybe you can check the openssl version？
SSL_accept() fail output msg @ dtls_server.cpp line:274 and line:294
