### ISSUE TITLE
Compilation failed on 9.3

### ISSUE THREAD

**Issue by alphaonex86** [paultan63/DTLS-epoll-example#2]
Hi, compilation failed on g++ 9.3 debian 11:

`make
g++ -g -g -O3 -I/usr/local/openssl/include -o dtls_server dtls_server.cpp my_cbio.cpp -L/usr/local/openssl/lib -Wl,-rpath=/usr/local/openssl/lib -lssl -lcrypto
In file included from dtls_server.cpp:18:
my_cbio.h:16:16: error: flexible array member ‘CustomBuffer::m_auchBuf’ not at end of ‘struct CustomBioData’
   16 |  unsigned char m_auchBuf[];
      |                ^~~~~~~~~
my_cbio.h:45:26: note: next member ‘sockaddr_storage CustomBioData::m_stClientAddr’ declared here
   45 |  struct sockaddr_storage m_stClientAddr;
      |                          ^~~~~~~~~~~~~~
my_cbio.h:43:8: note: in the definition of ‘struct CustomBioData’
   43 | struct CustomBioData{
      |        ^~~~~~~~~~~~~
my_cbio.h:16:16: error: flexible array member ‘CustomBuffer::m_auchBuf’ not at end of ‘struct UdpConnectInfo’
   16 |  unsigned char m_auchBuf[];
      |                ^~~~~~~~~
my_cbio.h:45:26: note: next member ‘sockaddr_storage CustomBioData::m_stClientAddr’ declared here
   45 |  struct sockaddr_storage m_stClientAddr;
      |                          ^~~~~~~~~~~~~~
dtls_server.cpp:45:8: note: in the definition of ‘struct UdpConnectInfo’
   45 | struct UdpConnectInfo{
      |        ^~~~~~~~~~~~~~
In file included from my_cbio.cpp:14:
my_cbio.h:16:16: error: flexible array member ‘CustomBuffer::m_auchBuf’ not at end of ‘struct CustomBioData’
   16 |  unsigned char m_auchBuf[];
      |                ^~~~~~~~~
my_cbio.h:45:26: note: next member ‘sockaddr_storage CustomBioData::m_stClientAddr’ declared here
   45 |  struct sockaddr_storage m_stClientAddr;
      |                          ^~~~~~~~~~~~~~
my_cbio.h:43:8: note: in the definition of ‘struct CustomBioData’
   43 | struct CustomBioData{
      |        ^~~~~~~~~~~~~
make: *** [Makefile:15: dtls_server] Error 1`

**Comment by paultan63** [comment]
I don't have a  g++ 9.3 environment. Maybe below can fix it：
unsigned char m_auchBuf[1];
